project:
  type: website

website:
  title: "DSAN 5000 Final Project"
  sidebar:
    contents:
      - href: Introduction.qmd
        text: Introduction
      - about.qmd
      - text: Code
        href: https://github.com/anly501/dsan-5000-project-jackyzhang1008.git
      - Data.qmd
      - Gathering.qmd
      - Cleaning.qmd
      - Exploration.qmd
      - Na√Øve_Bayes.qmd
      - Decision_tree.qmd
      - Reduction.qmd
      - Clustering.qmd
      - ARM.qmd
      - Conclusion.qmd

format:
  html:
    theme: cosmo
    toc: true



